version: "3.8"

services:
   app:
     image: urielwo/final_project:latest
     #build:
     #  context: ./
     ports: 
         - '8081:5000'
     working_dir: /app
     environment:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_DB: ${MYSQL_DB} 
        MYSQL_USER: ${MYSQL_USER} 
        MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
     #volumes: 
     #  - ~/branch/Course-project:/app/
     command: python3 myFlask.py
   
   mysql:
     image: mysql:latest
     environment:
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
     ports:
        - '3308:3306' # enter from linux
     volumes: 
       - /etc/mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d/

networks:
  default:
    external: false
    name: net
        

